import os
import uuid
from datetime import datetime
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.units import mm

# Ensure fonts directory exists or fallback to standard fonts
# Note: For production Japanese PDF, we need a font like IPAexGothic.
# For this mock, we will use standard Helvetica and ASCII text to avoid complex font setup issues in the demo environment,
# or we can try to use a system font if available. For safety, we stick to English/ASCII mock data or standard fonts.

class PDFGenerator:
    def __init__(self, output_dir="public/documents"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def _draw_header(self, c, title, subtitle=None):
        width, height = A4
        c.setFont("Helvetica-Bold", 20)
        c.drawString(20 * mm, height - 30 * mm, title)
        if subtitle:
            c.drawString(130 * mm, height - 30 * mm, subtitle)
        
        c.setFont("Helvetica", 12)
        c.drawString(20 * mm, height - 45 * mm, f"Date: {datetime.now().strftime('%Y-%m-%d')}")

    def _draw_footer(self, c):
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(20 * mm, 20 * mm, "Generated by IKIGAI Platform - Regulatory Compliance Demo")

    def generate_mortgage_application(self, user_data: dict, amount: int) -> str:
        filename = f"mortgage_application_{uuid.uuid4().hex[:8]}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        
        c = canvas.Canvas(filepath, pagesize=A4)
        width, height = A4
        
        self._draw_header(c, "MORTGAGE PRE-APPROVAL APPLICATION")
        c.drawString(20 * mm, height - 45 * mm, f"Application ID: {uuid.uuid4().hex}")
        
        # Applicant Details
        y = height - 70 * mm
        c.setFont("Helvetica-Bold", 14)
        c.drawString(20 * mm, y, "APPLICANT DETAILS")
        y -= 10 * mm
        
        c.setFont("Helvetica", 12)
        c.drawString(20 * mm, y, f"Name: {user_data.get('name', 'John Doe')}")
        y -= 8 * mm
        c.drawString(20 * mm, y, f"Annual Income: JPY {user_data.get('income', '0'):,}")
        y -= 8 * mm
        c.drawString(20 * mm, y, f"Employment: {user_data.get('employment', 'Unspecified')}")
        
        # Loan Details
        y -= 20 * mm
        c.setFont("Helvetica-Bold", 14)
        c.drawString(20 * mm, y, "LOAN REQUEST")
        y -= 10 * mm
        
        c.setFont("Helvetica", 12)
        c.drawString(20 * mm, y, f"Requested Amount: JPY {amount:,}")
        y -= 8 * mm
        c.drawString(20 * mm, y, "Term: 35 Years")
        y -= 8 * mm
        c.drawString(20 * mm, y, "Interest Type: Variable (0.475%)")
        
        self._draw_footer(c)
        
        c.save()
        return f"/documents/{filename}"

    def generate_purchase_offer(self, property_id: str, price: int, user_name: str) -> str:
        filename = f"purchase_offer_{uuid.uuid4().hex[:8]}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        
        c = canvas.Canvas(filepath, pagesize=A4)
        width, height = A4
        
        self._draw_header(c, "LETTER OF INTENT (BUYING OFFER)", "(買付証明書)")
        
        # To Seller
        y = height - 60 * mm
        c.drawString(20 * mm, y, "To Seller / Listing Agent")
        
        # Offer Details
        y -= 20 * mm
        c.setFont("Helvetica-Bold", 14)
        c.drawString(20 * mm, y, "OFFER DETAILS")
        y -= 10 * mm
        
        c.setFont("Helvetica", 12)
        c.drawString(20 * mm, y, f"Property ID: {property_id}")
        y -= 8 * mm
        c.drawString(20 * mm, y, f"Offer Price: JPY {price:,}")
        y -= 8 * mm
        c.drawString(20 * mm, y, f"Buyer: {user_name}")
        y -= 8 * mm
        c.drawString(20 * mm, y, "Conditions: Financing Contingency, Inspection Required")
        
        # Signature Line
        y -= 40 * mm
        c.line(20 * mm, y, 100 * mm, y)
        c.drawString(20 * mm, y - 5 * mm, "Buyer Signature")
        
        self._draw_footer(c)
        
        c.save()
        return f"/documents/{filename}"

    def generate_renovation_quote(self, property_id: str, breakdown: dict, total_cost: int, duration_weeks: int) -> str:
        filename = f"renovation_quote_{uuid.uuid4().hex[:8]}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        
        c = canvas.Canvas(filepath, pagesize=A4)
        width, height = A4
        
        self._draw_header(c, "RENOVATION ESTIMATE", "(見積書)")
        
        # Property Details
        y = height - 60 * mm
        c.setFont("Helvetica-Bold", 14)
        c.drawString(20 * mm, y, "PROPERTY DETAILS")
        y -= 10 * mm
        c.setFont("Helvetica", 12)
        c.drawString(20 * mm, y, f"Property ID: {property_id}")
        
        # Cost Breakdown
        y -= 25 * mm
        c.setFont("Helvetica-Bold", 14)
        c.drawString(20 * mm, y, "COST BREAKDOWN (JPY)")
        y -= 10 * mm
        
        c.setFont("Helvetica", 12)
        for item, cost in breakdown.items():
            c.drawString(20 * mm, y, f"- {item.title()}:")
            c.drawRightString(100 * mm, y, f"{cost:,}")
            y -= 8 * mm
            
        y -= 5 * mm
        c.line(20 * mm, y, 100 * mm, y)
        y -= 10 * mm
        c.setFont("Helvetica-Bold", 14)
        c.drawString(20 * mm, y, "TOTAL ESTIMATE")
        c.drawRightString(100 * mm, y, f"JPY {total_cost:,}")
        
        y -= 20 * mm
        c.setFont("Helvetica", 12)
        c.drawString(20 * mm, y, f"Estimated Duration: {duration_weeks} weeks")
        
        self._draw_footer(c)
        
        c.save()
        return f"/documents/{filename}"
